### ISSUE TITLE
Gør test suite uafhængig af gamle SQL-udtræk

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/fikspunktsregister#102]
Da fireapi nu er tilpas modent er det ikke længere nødvendigt at vedligeholde et test datasæt fra FIRE. Test suiten skal modificeres sådan at diverse tests selv populerer databasen med de det skal bruge.

Umiddelbart ser det ud til at der skal ændres i følgende filer:

``test/test_observation.py``
``test/test_punkt.py``
``test/test_srid.py``

**Comment by busstoptaktik** [comment]
Jeg kan ikke rigtigt få overblik over #100, #101, #102, #105. Er der lang vej endnu set fra din udkigspost?

**Comment by kbevers** [comment]
Den her er lukket. Jeg mangler at få opdateret DDL i #101 før den kan lukkes. Jeg skal nok komme til det, men som du ved er der nok at se til.
