### ISSUE TITLE
Documentation on readthedocs

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/fikspunktsregister#95]
ifht at sikre lige vilkår ifbm udbud baseret på FIRE APIet, ville det være grumme nyttigt om API-dokumentationen blev tilgængelig via readthedocs.

@AsgerPetersen - er dette en lille, eller en monsteropgave?

**Comment by kbevers** [comment]
Lukkes med #97. 

Se https://kortforsyningen.github.io/fikspunktsregister/
