### ISSUE TITLE
Flyt repo til Kortforsyningen/fikspunktregister

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/fikspunktsregister#96]
Formelt gør det selvfølgelig ikke nogen nævneværdig forskel hvor APIet bor - reelt vil det, ifbm. udbud, eliminere enhver rimelig mistanke om at Septima har en hjemmebanefordel.

Desuden vil det markere en formel overdragelse af koden.

@AsgerPetersen - kan dette (og #95) implementeres inden for et rimeligt timeantal?

**Comment by AsgerPetersen** [comment]
@kbevers Kan jeg evt få rettigheder til at oprette repos hos jer for en stund?
![image](https://user-images.githubusercontent.com/1392735/67938366-9e0d8900-fbcf-11e9-9e0f-878238935aa8.png)

**Comment by AsgerPetersen** [comment]
Jeg antager i øvrigt, at https://github.com/Septima/fire-gama også skal flyttes til Kortforsyningen.

**Comment by kbevers** [comment]
> @kbevers Kan jeg evt få rettigheder til at oprette repos hos jer for en stund?

Det tror jeg ikke jeg kan slippe afsted med uden at give dig adgang til alt for meget andet også. Jeg laver lige et par repos istedet og tildeler dig så mange rettigheder jeg kan istedet. 

> Jeg antager i øvrigt, at Septima/fire-gama også skal flyttes til Kortforsyningen.

Ja tak.

**Comment by AsgerPetersen** [comment]
Hmm, så kommer issues, bindinger til CI og den slags ikke med over.

**Comment by kbevers** [comment]
Oh, okay. Jeg ser hvad jeg kan gøre. So far har jeg oprettet to repos, fire-core og fire-gama, som du har fuld adgang til.

**Comment by kbevers** [comment]
Jeg har slettet de to repos igen og givet dig midlertidig adgang til at oprette repos hos Kortforsyningen

**Comment by AsgerPetersen** [comment]
Så, nu skulle de være ovre hos jer. Du kan sparke mig ud igen 😀

**Comment by kbevers** [comment]
Tak. Du er blevet sparket ud igen :)

**Comment by AsgerPetersen** [comment]
Må jeg blive contributor? Jeg har nogle ændringer på docs.

**Comment by AsgerPetersen** [comment]
Repo er flyttet
