### ISSUE TITLE
CircleCI virker ikke efter flytning

### ISSUE THREAD

**Issue by AsgerPetersen** [Kortforsyningen/fikspunktsregister#98]
CircleCI virker ikke ordentligt efter flytningen.

Jeg kan se, at jobbet for #96 er kørt på Septimas CircleCI, men det får aldrig leveret resultatet tilbage til repoet.

Kan @kbevers eventuelt kigge under Settings->Branches->Branch protection rules om der er noget spændende at se der? 

Indtil videre ville det nemmeste jo nok være, hvis det kunne køre videre på Septimas CircleCi.

**Comment by kbevers** [comment]
Umiddelbart ser det ikke ud til at der er noget spændende at se: 
![branch_protection](https://user-images.githubusercontent.com/13132571/67955383-d2df0780-fbf2-11e9-86a7-e3e68ecbfa4e.PNG)

**Comment by kbevers** [comment]
Lukket med https://github.com/Kortforsyningen/fikspunktsregister/pull/99
